[project]
name = "dear"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "equinox>=0.13.2",
    "feedparser>=6.0.12",
    "httpx>=0.28.1",
    "jax>=0.8.2",
    "tqdm>=4.67.1",
]
